### PR TITLE
Updated fonts and changed disabled button style

### PR DESCRIPTION
**Pull request by LightWayUp**
- Roboto fonts are updated from 2.001101 (2014) to 2.138
- Disabled button's text color is changed to be different from that of enabled button
- Added license information to places where possible
- Added Roboto fonts' NOTICE license file
- Updated uninstallation instructions to point out themes can now be reverted without removing Homebrew Channel save file
- Updated installation instructions to clarify parent folders should not be compressed
- Updated license information in README.md
- Updated multiple links in README.md to point to new URLs and to use https instead of http
- Fixed line breaks and headings in README.md
- Bumped version number and changed last release date

### CODE REVIEW

**Comment by LightWayUp** [comment]
Hello @ellsclytn, can you merge this change? This makes the theme properly display the difference between enabled buttons and disabled buttons ( which can be seen in the options screen ). Thanks!

**Comment by ellsclytn** [comment]
Hey, sorry for the delay. I'll give it a look over in a few hours time 🙂

**Comment by LightWayUp** [comment]
Thanks! 🙂

**Comment by ellsclytn** [comment]
Looks good. Thanks for doing this!

**Pull request merged**
